#!/bin/bash

echo "=================================================="
echo "  Environment Variable Guide"
echo "=================================================="
echo ""
echo "Set these in .env or your shell profile:"
echo ""
echo "  BINANCE_API_KEY=your_binance_key"
echo "  BINANCE_SECRET_KEY=your_binance_secret"
echo "  DEEPSEEK_API_KEY=your_llm_key"
echo "  TELEGRAM_BOT_TOKEN=your_telegram_bot_token"
echo "  TELEGRAM_CHAT_ID=your_telegram_chat_id"
echo ""
echo "Then start the Go runtime with:"
echo "  ./start.sh"
